############# K8S RESOURCES (GKE) MANAGEMENT BELOW ################

# ============================================================================
# KUBERNETES RESOURCES (Namespaces)
# ============================================================================

resource "kubernetes_namespace" "locust_ns" {
  metadata {
    name = var.namespaces.locust
    labels = {
      environment = "benchmarking"
    }
  }
}

resource "kubernetes_namespace" "java_apps_ns" {
  metadata {
    name = var.namespaces.java_apps
    labels = {
      environment = "production"
    }
  }
}

resource "kubernetes_namespace" "monitoring_ns" {
  metadata {
    name = var.namespaces.monitoring
    labels = {
      tool = "prometheus-grafana"
    }
  }
}


# ============================================================================
# JAVA APP DEPLOYMENT & SECRETS (CRITICAL SECTION)
# ============================================================================

# --- 0. Retrieve Password from Secret Manager ---
# Gets the password generated by the Infrastructure layer.
# Uses the dynamic Project ID variable.
data "google_secret_manager_secret_version" "db_pass" {
  project = var.gcp.project_id
  secret  = data.terraform_remote_state.infra.outputs.mongo_secret_resource_id
  version = "latest"
}

# --- 1. Create Kubernetes Secret (Dynamic & Sanitized) ---
# This constructs the MongoDB Connection String dynamically using the retrieved password.
resource "kubernetes_secret" "firestore_mongo_secret" {
  metadata {
    name      = "firestore-mongo-secret"
    namespace = kubernetes_namespace.java_apps_ns.metadata[0].name
  }

  data = {
    # EXACT KEY: "MONGO_DB_URI"
    # We use format() to insert variables into the connection string placeholders (%s).
    # Structure: mongodb://USER:PASS@HOST:PORT/DB_NAME?OPTIONS...
    
    MONGO_DB_URI = format(
      "mongodb://%s:%s@%s:443/%s?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false",
      
      # 1. User (From Infra Output)
      urlencode(data.terraform_remote_state.infra.outputs.mongo_user_name),
      
      # 2. Password (From Secret Manager)
      urlencode(data.google_secret_manager_secret_version.db_pass.secret_data),
      
      # 3. Host (From Infra Output)
      data.terraform_remote_state.infra.outputs.mongo_host_address,

      # 4. Database Name (Read from Infra State - Dynamic)
      data.terraform_remote_state.infra.outputs.firestore_database_name
    )
  }

  type = "Opaque"
}

# --- 2. Deployment ---
resource "kubernetes_deployment" "firestore_poc_app" {
  metadata {
    name      = "firestore-poc-service"
    namespace = kubernetes_namespace.java_apps_ns.metadata[0].name
    labels = {
      app = "firestore-poc"
    }
  }

  spec {
    replicas = var.scaling.java_replicas

    selector {
      match_labels = {
        app = "firestore-poc"
      }
    }

    template {
      metadata {
        labels = {
          app = "firestore-poc"
        }
      }

      spec {
        container {
          name  = "firestore-poc-container"
          image = var.images.java_app

          port {
            container_port = 8080
          }

          # This injects the Secret we created above as an Environment Variable
          env {
            name = "MONGO_DB_URI"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.firestore_mongo_secret.metadata[0].name
                key  = "MONGO_DB_URI"
              }
            }
          }
        }
      }
    }
  }
}

# --- 3. Service ---
resource "kubernetes_service" "firestore_poc_svc" {
  metadata {
    name      = "firestore-poc-service-lb"
    namespace = kubernetes_namespace.java_apps_ns.metadata[0].name
  }

  spec {
    selector = {
      app = kubernetes_deployment.firestore_poc_app.spec[0].template[0].metadata[0].labels.app
    }
    type = "ClusterIP" 
    port {
      port        = 80
      target_port = 8080
      protocol    = "TCP"
    }
  }
}


# ============================================================================
# LOCUST LOAD TESTING DEPLOYMENT (Cloud Native Architecture)
# ============================================================================

# --- 1. Locust Master Deployment ---
resource "kubernetes_deployment" "locust_master" {
  metadata {
    name      = "locust-master"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
    labels = {
      app = "locust-master"
    }
  }

  spec {
    replicas = 1
    selector {
      match_labels = {
        app = "locust-master"
      }
    }
    template {
      metadata {
        labels = {
          app = "locust-master"
        }
      }
      spec {
        container {
          name              = "locust-master"
          image             = var.images.locust_test
          image_pull_policy = "Always"

          port { container_port = 8089 }
          port { container_port = 5557 }
          port { container_port = 5558 }

          args = [
            "-f", "locustfile.py",
            "--master",
            "--loglevel", var.locust_config_loglevel
          ]

          # --- CONFIGURATION INJECTION ---
          
          # 1. Force Python to log immediately (Crucial for debugging)
          env {
            name  = "PYTHONUNBUFFERED"
            value = "1"
          }

          # 2. Config File Location (From variables)
          env {
            name  = "CONFIG_URI"
            value = var.locust_storage.config_uri 
          }
          
          # 3. Target Host (Internal K8s DNS)
          env {
            name  = "TARGET_HOST"
            value = "http://${kubernetes_service.firestore_poc_svc.metadata[0].name}.${kubernetes_namespace.java_apps_ns.metadata[0].name}.svc.cluster.local"
          }
        }
      }
    }
  }
}

# --- 2. SERVICE A: Public Web UI ---
resource "kubernetes_service" "locust_master_public" {
  metadata {
    name      = "locust-master-web"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
  }
  spec {
    selector = {
      app = kubernetes_deployment.locust_master.spec[0].template[0].metadata[0].labels.app
    }
    type = "LoadBalancer"
    port {
      name        = "web-ui"
      port        = 8089
      target_port = 8089
      protocol    = "TCP"
    }
  }
}

# --- 3. SERVICE B: Internal Communication ---
resource "kubernetes_service" "locust_master_internal" {
  metadata {
    name      = "locust-master-internal"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
  }
  spec {
    selector = {
      app = kubernetes_deployment.locust_master.spec[0].template[0].metadata[0].labels.app
    }
    type = "ClusterIP"
    
    # Corrected Syntax: Multi-line blocks
    port {
      name        = "web-api" 
      port        = 8089
      target_port = 8089
      protocol    = "TCP"
    }

    port {
      name        = "comms"
      port        = 5557
      target_port = 5557
      protocol    = "TCP"
    }
    
    port {
      name        = "stats"
      port        = 5558
      target_port = 5558
      protocol    = "TCP"
    }
  }
}

# --- 4. Locust Worker Deployment ---
resource "kubernetes_deployment" "locust_worker" {
  metadata {
    name      = "locust-worker"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
    labels = {
      app = "locust-worker"
    }
  }

  spec {
    replicas = var.scaling.locust_workers
    selector {
      match_labels = {
        app = "locust-worker"
      }
    }
    template {
      metadata {
        labels = {
          app = "locust-worker"
        }
      }
      spec {
        container {
          name              = "locust-worker"
          image             = var.images.locust_test
          image_pull_policy = "Always"

          args = [
            "-f", "locustfile.py",
            "--worker",
            "--master-host=${kubernetes_service.locust_master_internal.metadata[0].name}.${kubernetes_namespace.locust_ns.metadata[0].name}.svc.cluster.local",
            "--loglevel", var.locust_config_loglevel
          ]

          # --- CONFIGURATION INJECTION (Same as Master) ---
          
          env {
            name  = "PYTHONUNBUFFERED"
            value = "1"
          }

          env {
            name  = "CONFIG_URI"
            value = var.locust_storage.config_uri
          }
          
          env {
            name  = "TARGET_HOST"
            value = "http://${kubernetes_service.firestore_poc_svc.metadata[0].name}.${kubernetes_namespace.java_apps_ns.metadata[0].name}.svc.cluster.local"
          }
        }
      }
    }
  }
  
  depends_on = [kubernetes_service.locust_master_internal]
}


# ============================================================================
# LOCUST EXPORTER (Metrics)
# ============================================================================

resource "kubernetes_deployment" "locust_exporter" {
  metadata {
    name      = "locust-exporter"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
    labels = {
      app = "locust-exporter"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "locust-exporter"
      }
    }

    template {
      metadata {
        labels = {
          app = "locust-exporter"
        }
        annotations = {
          "prometheus.io/scrape" = "true"
          "prometheus.io/port"   = "9191"
          "prometheus.io/path"   = "/metrics"
        }
      }

      spec {
        container {
          name  = "locust-exporter"
          image = var.images.locust_exporter
          image_pull_policy = "Always"

          port {
            name           = "metrics"
            container_port = 9191
          }
          
          env {
            name = "LOCUST_HOST"
            value = "http://${kubernetes_service.locust_master_internal.metadata[0].name}.${kubernetes_namespace.locust_ns.metadata[0].name}.svc.cluster.local:8089/"
          }

          env {
            name  = "EXPORTER_PORT"
            value = "9191"
          }

          env {
            name  = "PYTHONUNBUFFERED"
            value = "1"
          }

          env {
            name  = "LOG_LEVEL"
            value = var.locust_config_loglevel
          }
        }
      }
    }
  }

  depends_on = [kubernetes_service.locust_master_internal]
}

resource "kubernetes_service" "locust_exporter_svc" {
  metadata {
    name      = "locust-exporter-service"
    namespace = kubernetes_namespace.locust_ns.metadata[0].name
    labels = {
      app = "locust-exporter"
    }
  }
  spec {
    selector = {
      app = kubernetes_deployment.locust_exporter.spec[0].template[0].metadata[0].labels.app
    }
    type = "ClusterIP"
    port {
      name        = "metrics"
      port        = 9191
      target_port = 9191
      protocol    = "TCP"
    }
  }
}


# ============================================================================
# MONITORING STACK (Prometheus & Grafana)
# ============================================================================

# --- RBAC ---
resource "kubernetes_cluster_role" "prometheus_reader" {
  metadata {
    name = "prometheus-reader"
  }
  rule {
    api_groups = [""]
    resources  = ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs      = ["get", "list", "watch"]
  }
  rule {
    api_groups = ["extensions"]
    resources  = ["ingresses"]
    verbs      = ["get", "list", "watch"]
  }
  rule {
    non_resource_urls = ["/metrics"]
    verbs             = ["get"]
  }
}

resource "kubernetes_cluster_role_binding" "prometheus_reader_binding" {
  metadata {
    name = "prometheus-reader-binding"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = kubernetes_cluster_role.prometheus_reader.metadata[0].name
  }
  subject {
    kind      = "ServiceAccount"
    name      = "default"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
}

# --- Kube State Metrics ---
resource "kubernetes_deployment" "ksm" {
  metadata {
    name      = "kube-state-metrics"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "kube-state-metrics"
    }
  }
  spec {
    replicas = 1
    selector {
      match_labels = {
        app = "kube-state-metrics"
      }
    }
    template {
      metadata {
        labels = {
          app = "kube-state-metrics"
        }
      }
      spec {
        service_account_name = "default"
        container {
          name  = "kube-state-metrics"
          image = "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2"
          
          port {
            container_port = 8080
            name           = "http-metrics"
          }
          port {
            container_port = 8081
            name           = "telemetry"
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "ksm_service" {
  metadata {
    name      = "kube-state-metrics"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "kube-state-metrics"
    }
  }
  spec {
    selector = {
      app = kubernetes_deployment.ksm.spec[0].template[0].metadata[0].labels.app
    }
    type = "ClusterIP"
    port {
      name        = "http-metrics"
      port        = 8080
      target_port = 8080
    }
  }
}

# --- Node Exporter ---
resource "kubernetes_daemonset" "node_exporter" {
  metadata {
    name = "node-exporter"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "node-exporter"
    }
  }
  spec {
    selector {
      match_labels = {
        app = "node-exporter"
      }
    }
    template {
      metadata {
        labels = {
          app = "node-exporter"
        }
      }
      spec {
        host_network = true
        container {
          name = "node-exporter"
          image = "quay.io/prometheus/node-exporter:v1.8.1"
          args = ["--path.rootfs=/host"]
          port {
            container_port = 9100
            name = "metrics"
          }
          volume_mount {
            name = "rootfs"
            mount_path = "/host"
            read_only = true
          }
        }
        volume {
          name = "rootfs"
          host_path {
            path = "/"
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "node_exporter_service" {
  metadata {
    name = "node-exporter"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "node-exporter"
    }
  }
  spec {
    selector = {
      app = "node-exporter"
    }
    port {
      name = "metrics"
      port = 9100
      target_port = 9100
    }
  }
}

# --- Prometheus Config ---
resource "kubernetes_config_map" "prometheus_config" {
  metadata {
    name      = "prometheus-config"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  data = {
    "prometheus.yml" = <<EOF
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'locust'
    static_configs:
      - targets:
          - 'locust-exporter-service.${var.namespaces.locust}.svc.cluster.local:9191'

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets:
          - 'kube-state-metrics.${var.namespaces.monitoring}.svc.cluster.local:8080'

  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

  - job_name: "node-exporter"
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: node-exporter
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        regex: ${var.namespaces.monitoring}
        action: keep
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
EOF
  }
}

resource "kubernetes_persistent_volume_claim" "prometheus_storage" {
  metadata {
    name      = "prometheus-storage"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = var.storage.prometheus
      }
    }
    storage_class_name = "standard-rwo"
  }
  wait_until_bound = false
}

resource "kubernetes_deployment" "prometheus" {
  metadata {
    name      = "prometheus"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "prometheus"
    }
  }
  spec {
    replicas = 1
    selector {
      match_labels = {
        app = "prometheus"
      }
    }
    template {
      metadata {
        labels = {
          app = "prometheus"
        }
      }
      spec {
        security_context {
          run_as_user  = 65534
          run_as_group = 65534
          fs_group     = 65534
        }
        container {
          name  = "prometheus"
          image = "prom/prometheus:latest"
          args = [
            "--config.file=/etc/prometheus/prometheus.yml",
            "--storage.tsdb.path=/prometheus/",
            "--storage.tsdb.retention.time=${var.prometheus_config.retention_time}",
            "--storage.tsdb.retention.size=${var.prometheus_config.retention_size}",
            "--web.enable-lifecycle"
          ]
          port {
            container_port = 9090
          }
          volume_mount {
            name       = "config-volume"
            mount_path = "/etc/prometheus/"
          }
          volume_mount {
            name       = "storage-volume"
            mount_path = "/prometheus/"
          }
        }
        volume {
          name = "config-volume"
          config_map {
            name = kubernetes_config_map.prometheus_config.metadata[0].name
          }
        }
        volume {
          name = "storage-volume"
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.prometheus_storage.metadata[0].name
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "prometheus_service" {
  metadata {
    name      = "prometheus-service"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  spec {
    selector = {
      app = kubernetes_deployment.prometheus.spec[0].template[0].metadata[0].labels.app
    }
    type = "ClusterIP"
    port {
      port        = 80
      target_port = 9090
    }
  }
}


# ==============================================================================
# GRAFANA COMPLETE SETUP (Sidecar + Public URL Variable + No Limits)
# ==============================================================================

# --- 1. ConfigMaps ---

resource "kubernetes_config_map" "grafana_datasources" {
  metadata {
    name      = "grafana-datasources"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  data = {
    "datasource.yaml" = <<EOF
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service.${var.namespaces.monitoring}.svc.cluster.local
    isDefault: true
    editable: true
    uid: PBFA97CFB590B2093

  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    uid: gcp-monitoring-uid
    jsonData:
      authenticationType: gce
      defaultProject: "${var.gcp.project_id}"
EOF
  }
}

resource "kubernetes_config_map" "grafana_dashboard_provider" {
  metadata {
    name      = "grafana-dashboard-provider"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  data = {
    "dashboard.yaml" = <<EOF
apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /var/lib/grafana/dashboards
EOF
  }
}

resource "kubernetes_config_map" "grafana_dashboards_json" {
  metadata {
    name      = "grafana-dashboards-json"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  data = {
    "locust-dashboard.json"       = file("${path.module}/dashboards/locust-dashboard.json")
    "k8s-resource-dashboard.json" = file("${path.module}/dashboards/k8s-resource-dashboard.json")
    "firestore-dashboard.json"    = file("${path.module}/dashboards/firestore-dashboard.json")
  }
}

# --- 2. PVC (Storage) ---

resource "kubernetes_persistent_volume_claim" "grafana_storage" {
  metadata {
    name      = "grafana-storage"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = var.storage.grafana
      }
    }
    storage_class_name = "standard-rwo"
  }
  wait_until_bound = false
}

# --- 3. Deployment (The Core Logic) ---

resource "kubernetes_deployment" "grafana" {
  metadata {
    name      = "grafana"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
    labels = {
      app = "grafana"
    }
  }
  spec {
    replicas = 1
    
    # STRATEGY: Recreate
    # CRITICAL: Forces K8s to terminate the old pod (releasing the RWO volume)
    # before starting the new one. Prevents "Multi-Attach error".
    strategy {
      type = "Recreate"
    }

    selector {
      match_labels = {
        app = "grafana"
      }
    }
    template {
      metadata {
        labels = {
          app = "grafana"
        }
      }
      spec {
        security_context {
          fs_group = 472
        }

        # --- CONTAINER A: Grafana (Main App) ---
        container {
          name  = "grafana"
          image = "grafana/grafana:latest"
          port {
            container_port = 3000
          }

          # 1. PUBLIC URL (Fix for "Failed to fetch")
          # Uses the variable defined in variables.tf (e.g., http://136.114.x.x/)
          # This ensures the browser asks the correct server for the image.
          env {
            name  = "GF_SERVER_ROOT_URL"
            value = var.grafana_root_url
          }
          
          # 2. RENDERER CONNECTION (Internal)
          # Communicates with the sidecar via localhost (127.0.0.1).
          env {
            name  = "GF_RENDERING_SERVER_URL"
            value = "http://127.0.0.1:8081/render"
          }
          env {
            name  = "GF_RENDERING_CALLBACK_URL"
            value = "http://127.0.0.1:3000/"
          }
          
          # 3. TIMEOUTS (For heavy dashboards)
          # Increases wait time to 60s to prevent timeouts on LoadBalancer.
          env {
             name = "GF_RENDERING_TIMEOUT"
             value = "60" 
          }
          # 4. LOGGING (Debug rendering issues)
          env {
            name  = "GF_LOG_FILTERS"
            value = "rendering:debug"
          }

          # Volume Mounts
          volume_mount {
            mount_path = "/var/lib/grafana"
            name       = "grafana-storage"
          }
          volume_mount {
            mount_path = "/etc/grafana/provisioning/datasources/datasource.yaml"
            sub_path   = "datasource.yaml"
            name       = "provisioning-datasources"
          }
          volume_mount {
            mount_path = "/etc/grafana/provisioning/dashboards/dashboard.yaml"
            sub_path   = "dashboard.yaml"
            name       = "provisioning-dashboards-provider"
          }
          volume_mount {
            mount_path = "/var/lib/grafana/dashboards"
            name       = "provisioning-dashboards-json"
          }
        }

        # --- CONTAINER B: Image Renderer (Sidecar) ---
        container {
          name  = "grafana-image-renderer"
          image = "grafana/grafana-image-renderer:latest"
          
          port {
            container_port = 8081
          }

          # Force listening on all interfaces (0.0.0.0) inside the pod
          env {
            name = "HTTP_HOST"
            value = "0.0.0.0"
          }
          
          # NOTE: No resource limits specified (BestEffort mode).
          # This allows the renderer to use all available node memory if needed.
        }

        # --- Volumes ---
        volume {
          name = "grafana-storage"
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.grafana_storage.metadata[0].name
          }
        }
        volume {
          name = "provisioning-datasources"
          config_map {
            name = kubernetes_config_map.grafana_datasources.metadata[0].name
          }
        }
        volume {
          name = "provisioning-dashboards-provider"
          config_map {
            name = kubernetes_config_map.grafana_dashboard_provider.metadata[0].name
          }
        }
        volume {
          name = "provisioning-dashboards-json"
          config_map {
            name = kubernetes_config_map.grafana_dashboards_json.metadata[0].name
          }
        }
      }
    }
  }
}

# --- 4. Service (LoadBalancer) ---

resource "kubernetes_service" "grafana_web" {
  metadata {
    name      = "grafana-web"
    namespace = kubernetes_namespace.monitoring_ns.metadata[0].name
  }
  spec {
    selector = {
      app = kubernetes_deployment.grafana.spec[0].template[0].metadata[0].labels.app
    }
    type = "LoadBalancer"
    port {
      port        = 80
      target_port = 3000
      protocol    = "TCP"
    }
  }
}