name: 'Deploy: Details'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/bookinfo/details/**'
      - 'environments/gcp-env-demo/k8s-manifests/02-details.yaml'
  workflow_dispatch:

concurrency:
  group: "details-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  call-shared-pipeline:
    uses: ./.github/workflows/shared-k8s-app-pipeline.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      app_name: 'details'
      app_dir: 'src/bookinfo/details'
