name: 'Deploy: Reviews'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/bookinfo/reviews/**'
      - 'environments/gcp-env-demo/k8s-manifests/03-reviews.yaml'
  workflow_dispatch:

concurrency:
  group: "reviews-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  call-shared-pipeline:
    uses: ./.github/workflows/shared-k8s-app-pipeline.yml
    with:
      app_name: 'reviews'
      app_dir: 'src/bookinfo/reviews'
