name: 'Deploy K8s Apps (Terraform) Test'

on:
  push:
    branches:
      - 'main'
    # Only wake up if there are changes in the apps folder
    paths:
      - 'environments/gcp-env-demo/k8s-apps/**'
  workflow_dispatch: # Allows you to run it manually from GitHub

# ============================================================================
# CONCURRENCY (Auto-cancel previous redundant runs)
# ============================================================================
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  k8s-deploy:
    name: 'Terraform Apply K8s Apps'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    # Required permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@v4' 

      # 1. Authentication
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/697350290405/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          project_id: 'developer-sandbox-489120'

      # 2. Install Terraform on the GitHub runner
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      # 3. Initialize Terraform (downloads GCP and K8s providers)
      - name: 'Terraform Init'
        working-directory: environments/gcp-env-demo/k8s-apps
        run: terraform init

      # 4. Deploy the app (auto-approve bypasses manual confirmation)
      - name: 'Terraform Apply'
        working-directory: environments/gcp-env-demo/k8s-apps
        run: terraform apply -auto-approve