name: 'Deploy Infra (Terraform)'

on:
  push:
    branches:
      - 'main'
    # Only wake up if there are changes in the infrastructure or modules.
    paths:
      - 'environments/gcp-env-demo/infrastructure/**'
      - 'modules/**'
  workflow_dispatch: # Allows you to run it manually from GitHub
    # Added manual input to gate the apply step
    inputs:
      run_apply:
        description: 'Run Terraform Apply? (Check to create/modify infrastructure)'
        required: true
        type: boolean
        default: false

jobs:
  terraform-deploy:
    name: 'Terraform Apply'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/697350290405/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          project_id: 'developer-sandbox-489120'

      - name: 'Set up Terraform'
        uses: 'hashicorp/setup-terraform@v3'

      - name: 'Terraform Init'
        working-directory: environments/gcp-env-demo/infrastructure
        run: terraform init

      # Always run a plan so we can see what will change (Dry-run)
      - name: 'Terraform Plan'
        working-directory: environments/gcp-env-demo/infrastructure
        run: terraform plan

      # The "Freno de Mano" / Manual Gate
      # This step will ONLY execute if triggered manually via GitHub Actions UI AND the checkbox is ticked
      - name: 'Terraform Apply'
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_apply == true }}
        working-directory: environments/gcp-env-demo/infrastructure
        run: terraform apply -auto-approve