name: 'Deploy K8s Apps'

on:
  push:
    branches:
      - 'main'
    # Only wake up if there are changes in the apps
    paths:
      - 'environments/gcp-env-demo/k8s-apps/**'
  workflow_dispatch: # Allows you to run it manually from GitHub

jobs:
  k8s-deploy:
    name: 'Kubernetes Apply'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/697350290405/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          project_id: 'developer-sandbox-489120'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Get GKE Credentials'
        run: gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER_NAME }} --region ${{ vars.GKE_CLUSTER_REGION }} --project ${{ vars.GCP_PROJECT_ID }}

      - name: 'Deploy to GKE'
        working-directory: environments/gcp-env-demo/k8s-apps
        run: kubectl apply -f .